### PR TITLE
Add unique feature identifier

### PR DESCRIPTION
**Pull request by LePetitTim**

### CODE REVIEW

**Comment by LePetitTim** [comment]
We should not have 2 identifier with the same uuid. Layer-processing create the centroid of an object and use the same identifier. It should not be possible because we use the identifier for viewsets. Then when we want to get an object, we get an error.

**Review by jrmi — CHANGES_REQUESTED** [review]
Need big changes on customer to handle this. We should discuss that.

**Comment by submarcos** [comment]
https://github.com/Terralego/django-geostore/issues/57

**Comment by submarcos** [comment]
https://github.com/Terralego/django-geostore/issues/56

**Pull request closed without merging**
